package interfaz;

import conexion.Conexion;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.sql.*;
import javax.sound.sampled.*;
import javax.swing.*;
import main.Login;

/**
 *
 * @author chris
 */
public class AltaClientes extends JFrame implements Interfaz, ActionListener {

    public AltaClientes() {
        initComponents();
        jPanel2.setBackground(Color.white);
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());
        rootaltacliente.setText((ventana.getNombreroot()));
        setTitle("BDPaq");
        BotonLimpiar.addActionListener(this);

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
        rootaltacliente.setText(nombreusuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        texfieldnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textfieldapellidos = new javax.swing.JTextField();
        fielddni = new javax.swing.JTextField();
        texfielddireccion = new javax.swing.JTextField();
        texfieldtelefono = new javax.swing.JTextField();
        texfieldemail = new javax.swing.JTextField();
        checkhombre = new javax.swing.JCheckBox();
        checkmujer = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rootaltacliente = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane2.setViewportView(jEditorPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 450, 0));

        jPanel4.setBackground(new java.awt.Color(45, 49, 66));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(45, 49, 66));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 270, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        texfieldnombre.setBackground(new java.awt.Color(248, 248, 248));
        texfieldnombre.setForeground(new java.awt.Color(204, 204, 204));
        texfieldnombre.setBorder(null);
        texfieldnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfieldnombreActionPerformed(evt);
            }
        });
        texfieldnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texfieldnombreKeyTyped(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Apellidos:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("DNI:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Direccion:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Email:");

        textfieldapellidos.setBackground(new java.awt.Color(248, 248, 248));
        textfieldapellidos.setForeground(new java.awt.Color(255, 255, 255));
        textfieldapellidos.setBorder(null);
        textfieldapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldapellidosActionPerformed(evt);
            }
        });
        textfieldapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldapellidosKeyTyped(evt);
            }
        });

        fielddni.setBackground(new java.awt.Color(248, 248, 248));
        fielddni.setForeground(new java.awt.Color(204, 204, 204));
        fielddni.setBorder(null);
        fielddni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fielddniKeyTyped(evt);
            }
        });

        texfielddireccion.setBackground(new java.awt.Color(248, 248, 248));
        texfielddireccion.setForeground(new java.awt.Color(204, 204, 204));
        texfielddireccion.setBorder(null);
        texfielddireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texfielddireccionKeyTyped(evt);
            }
        });

        texfieldtelefono.setBackground(new java.awt.Color(248, 248, 248));
        texfieldtelefono.setForeground(new java.awt.Color(255, 255, 255));
        texfieldtelefono.setBorder(null);
        texfieldtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texfieldtelefonoKeyTyped(evt);
            }
        });

        texfieldemail.setBackground(new java.awt.Color(248, 248, 248));
        texfieldemail.setForeground(new java.awt.Color(204, 204, 204));
        texfieldemail.setBorder(null);
        texfieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfieldemailActionPerformed(evt);
            }
        });
        texfieldemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texfieldemailKeyTyped(evt);
            }
        });

        checkhombre.setText("Hombre");
        checkhombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkhombreActionPerformed(evt);
            }
        });

        checkmujer.setText("Mujer");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel11.setText("Sexo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(texfieldnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fielddni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texfieldtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(checkhombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkmujer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(texfieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textfieldapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(texfielddireccion)
                                .addComponent(jSeparator5)
                                .addComponent(jSeparator7))))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texfieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(textfieldapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fielddni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(texfielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(texfieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(texfieldtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(checkhombre)
                    .addComponent(checkmujer))
                .addGap(21, 21, 21))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 240));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajarob.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 460, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO ALTA CLIENTES");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        BotonGuardar.setText("Guardar");
        BotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseExited(evt);
            }
        });
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonLimpiarMouseExited(evt);
            }
        });
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 54, 30));

        rootaltacliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(rootaltacliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 60, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed

    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        notificacion();
        nombre = texfieldnombre.getText();
        apellidos = textfieldapellidos.getText();
        dni = fielddni.getText();
        direccion = texfielddireccion.getText();
        try {
            ResultSet resultado = null;
            Connection cn = Conexion.conectar();
            String verificar = "SELECT * FROM clientes WHERE DniCliente = ?";
            PreparedStatement enviarVerificacion = cn.prepareStatement(verificar);
            enviarVerificacion.setString(1, dni);
            resultado = enviarVerificacion.executeQuery();
            if (!resultado.next()) {
                if (checkhombre.isSelected() && checkmujer.isSelected()) {
                    JOptionPane.showMessageDialog(null, "Solo puedes escoger un solo tipo de sexo");
                } else {
                    if (!checkmujer.isSelected() && !checkhombre.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Debes seleccionar al menos un sexo");
                    } else {
                        verificarCheck();
                        email = texfieldemail.getText();
                        if (nombre.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || direccion.isEmpty() || texfieldtelefono.getText().length() == 0 || email.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Debes rellenar los campos vacios");
                        } else if (fielddni.getText().length() != 9) {

                            JOptionPane.showMessageDialog(null, "Campo DNI invalido");
                        } else {
                            int opcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro?");
                            if (opcion == JOptionPane.YES_OPTION) {
                                insertDat(nombre, apellidos, dni, direccion, Integer.parseInt(texfieldtelefono.getText()), email, sexo);
                                JOptionPane.showMessageDialog(null, "Datos guardados");
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "DNI ya registrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La base de datos no esta activa");
        }


    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void texfieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfieldemailActionPerformed

    private void textfieldapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldapellidosActionPerformed
        // TODOh add your handling code here:
    }//GEN-LAST:event_textfieldapellidosActionPerformed

    private void texfieldnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfieldnombreActionPerformed

    }//GEN-LAST:event_texfieldnombreActionPerformed

    private void checkhombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkhombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkhombreActionPerformed

    private void texfieldnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texfieldnombreKeyTyped
        texfieldnombre.setForeground(Color.black);
    }//GEN-LAST:event_texfieldnombreKeyTyped

    private void fielddniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fielddniKeyTyped
        fielddni.setForeground(Color.black);
    }//GEN-LAST:event_fielddniKeyTyped

    private void texfieldtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texfieldtelefonoKeyTyped
        texfieldtelefono.setForeground(Color.black);
    }//GEN-LAST:event_texfieldtelefonoKeyTyped

    private void textfieldapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldapellidosKeyTyped
        textfieldapellidos.setForeground(Color.black);
    }//GEN-LAST:event_textfieldapellidosKeyTyped

    private void texfielddireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texfielddireccionKeyTyped
        texfielddireccion.setForeground(Color.black);
    }//GEN-LAST:event_texfielddireccionKeyTyped

    private void texfieldemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texfieldemailKeyTyped
        texfieldemail.setForeground(Color.black);
    }//GEN-LAST:event_texfieldemailKeyTyped

    private void BotonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseEntered
        BotonGuardar.setBackground(new Color(45, 49, 66));
        BotonGuardar.setForeground(Color.white);
    }//GEN-LAST:event_BotonGuardarMouseEntered

    private void BotonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseExited
        BotonGuardar.setBackground(new Color(255, 255, 255));
        BotonGuardar.setForeground(Color.black);
    }//GEN-LAST:event_BotonGuardarMouseExited

    private void BotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLimpiarMouseEntered
        BotonLimpiar.setBackground(new Color(45, 49, 66));
        BotonLimpiar.setForeground(Color.white);
    }//GEN-LAST:event_BotonLimpiarMouseEntered

    private void BotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLimpiarMouseExited
        BotonLimpiar.setBackground(new Color(255, 255, 255));
        BotonLimpiar.setForeground(Color.black);
    }//GEN-LAST:event_BotonLimpiarMouseExited

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        BotonVolver.setBackground(new Color(255, 255, 255));
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45, 49, 66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JCheckBox checkhombre;
    private javax.swing.JCheckBox checkmujer;
    private javax.swing.JTextField fielddni;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JLabel rootaltacliente;
    private javax.swing.JTextField texfielddireccion;
    private javax.swing.JTextField texfieldemail;
    private javax.swing.JTextField texfieldnombre;
    private javax.swing.JTextField texfieldtelefono;
    private javax.swing.JTextField textfieldapellidos;
    // End of variables declaration//GEN-END:variables

    public void insertDat(String nombre, String apellidos, String dni, String direccion, int telefono, String email, String sexo) {
        String query = "INSERT INTO clientes(NombreCliente,ApellidoCliente,DniCliente,DireccionCliente,TelefonoCliente,EmailCliente,Sexo) VALUES (?,?,?,?,?,?,?)";
        try {

            Connection cn = Conexion.conectar();
            PreparedStatement enviarConsultas = cn.prepareStatement(query);
            enviarConsultas.setString(1, nombre);
            enviarConsultas.setString(2, apellidos);
            enviarConsultas.setString(3, dni);
            enviarConsultas.setString(4, direccion);
            enviarConsultas.setInt(5, telefono);
            enviarConsultas.setString(6, email);
            enviarConsultas.setString(7, sexo);
            enviarConsultas.executeUpdate();
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error" + e);
        }
    }

    @Override
    public void notificacion() {
        try {
            // Carga el archivo de sonido
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);

            // Obtiene el formato de audio
            AudioFormat format = audioStream.getFormat();

            // Crea una fuente de datos de audio
            DataLine.Info info = new DataLine.Info(Clip.class, format);

            // Abre el clip de audio
            Clip clip = (Clip) AudioSystem.getLine(info);
            clip.open(audioStream);

            // Agrega un LineListener para detectar cuando finaliza la reproducción del clip
            clip.addLineListener(new LineListener() {
                @Override
                public void update(LineEvent event) {
                    if (event.getType() == LineEvent.Type.STOP) {
                    }
                }
            });

            // Reproduce el sonido
            clip.start();
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException e) {
            e.printStackTrace();
        }
    }

    public void verificarCheck() {
        if (checkhombre.isSelected()) {
            sexo = "H";

        } else {
            sexo = "M";
        }

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object escucha = e.getSource();
        if (escucha == BotonLimpiar) {
            texfieldnombre.setText(" ");
            textfieldapellidos.setText("");
            texfielddireccion.setText("");
            texfieldtelefono.setText("");
            texfieldemail.setText("");
            textfieldapellidos.setText("");
            fielddni.setText("");
        }
    }

    String soundFilePath = "C:\\Users\\chris\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\sonidos\\notificacion.wav";
    File sonido = new File(soundFilePath);
    public String nombre;
    public String direccion;
    public int telefono;
    public String email;
    public String dni;
    public String apellidos;
    boolean bandera = false;
    public static String nombreusuario = "";
    Login log = new Login();
    int xMouse, yMouse;
    String sexo;
    VentanaPrincipal ventana = new VentanaPrincipal();

}
