package interfaz;

import conexion.Conexion;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.*;

/**
 *
 * @author chris
 */
public class Altavehi extends javax.swing.JFrame implements ActionListener, Interfaz {

    public Altavehi() {
        VentanaMenu menu = new VentanaMenu();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());
        rootvehi.setText(menu.LabelRoot.getText());
        setTitle("BDPaq");
        BotonLimpiar.addActionListener(this);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldmodelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldcapacidad = new javax.swing.JTextField();
        fieldplaca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        interrogacion = new javax.swing.JLabel();
        fieldestado = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        BotonGuardar = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rootvehi = new javax.swing.JLabel();
        BotonLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 49, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Modelo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 19, 58, -1));

        fieldmodelo.setBackground(new java.awt.Color(248, 248, 248));
        fieldmodelo.setForeground(new java.awt.Color(204, 204, 204));
        fieldmodelo.setBorder(null);
        fieldmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldmodeloActionPerformed(evt);
            }
        });
        fieldmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldmodeloKeyTyped(evt);
            }
        });
        jPanel2.add(fieldmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 15, 115, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Capacidad:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 67, -1, -1));

        fieldcapacidad.setBackground(new java.awt.Color(248, 248, 248));
        fieldcapacidad.setForeground(new java.awt.Color(204, 204, 204));
        fieldcapacidad.setBorder(null);
        fieldcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldcapacidadKeyTyped(evt);
            }
        });
        jPanel2.add(fieldcapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 63, 115, 20));

        fieldplaca.setBackground(new java.awt.Color(248, 248, 248));
        fieldplaca.setForeground(new java.awt.Color(204, 204, 204));
        fieldplaca.setBorder(null);
        fieldplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldplacaActionPerformed(evt);
            }
        });
        fieldplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldplacaKeyTyped(evt);
            }
        });
        jPanel2.add(fieldplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 120, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Placa:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 37, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Marca");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 37, -1));

        fieldmarca.setBackground(new java.awt.Color(248, 248, 248));
        fieldmarca.setForeground(new java.awt.Color(204, 204, 204));
        fieldmarca.setBorder(null);
        fieldmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldmarcaKeyTyped(evt);
            }
        });
        jPanel2.add(fieldmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, 120, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 113, 60, 22));
        jPanel2.add(interrogacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 202, 15, 22));

        fieldestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Mantenimiento" }));
        jPanel2.add(fieldestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 120, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 120, 10));

        jPanel3.setBackground(new java.awt.Color(45, 49, 66));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 220, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 480, 170));

        BotonGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseExited(evt);
            }
        });
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        BotonVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 50, 20));

        rootvehi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rootvehi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(rootvehi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 70, 20));

        BotonLimpiar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonLimpiarMouseExited(evt);
            }
        });
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 540, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajarob.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 440, 180));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTA VEHICULOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldmodeloActionPerformed

    }//GEN-LAST:event_fieldmodeloActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed

    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        marca = fieldmarca.getText();
        modelo = fieldmodelo.getText();
        placa = fieldplaca.getText();

        estado = fieldestado.getSelectedItem().toString();

        ResultSet resultado = null;
        if (capacidad > 9 || capacidad < 0) {
            JOptionPane.showMessageDialog(null, "Campo capacidad: invalido (1-9)", "Error", JOptionPane.WARNING_MESSAGE);

        } else if (marca.isEmpty() || modelo.isEmpty() || placa.isEmpty() || estado.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar los campos vacios");
        } else {

            try {
                Connection cn = Conexion.conectar();
                String verificar = "SELECT * FROM vehiculos WHERE PlacaVehiculo = ?";
                PreparedStatement enviarVerificacion = cn.prepareStatement(verificar);
                enviarVerificacion.setString(1, placa);
                resultado = enviarVerificacion.executeQuery();
                if (!resultado.next()) {
                    insertDat(marca, modelo, placa, Integer.parseInt(fieldcapacidad.getText()), estado);
                    notificacion();
                    JOptionPane.showMessageDialog(null, "Guardado", "", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Campo placa: Ya existente");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Campo placa: Ya existente");
            }
        }


    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void fieldplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldplacaActionPerformed

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45, 49, 66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        BotonVolver.setBackground(new Color(255, 255, 255));
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLimpiarMouseEntered
        BotonLimpiar.setBackground(new Color(45, 49, 66));
        BotonLimpiar.setForeground(Color.white);
    }//GEN-LAST:event_BotonLimpiarMouseEntered

    private void BotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLimpiarMouseExited
        BotonLimpiar.setBackground(new Color(255, 255, 255));
        BotonLimpiar.setForeground(Color.black);
    }//GEN-LAST:event_BotonLimpiarMouseExited

    private void BotonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseEntered
        BotonGuardar.setBackground(new Color(45, 49, 66));
        BotonGuardar.setForeground(Color.white);
    }//GEN-LAST:event_BotonGuardarMouseEntered

    private void BotonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseExited
        BotonGuardar.setBackground(new Color(255, 255, 255));
        BotonGuardar.setForeground(Color.black);
    }//GEN-LAST:event_BotonGuardarMouseExited

    private void fieldmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldmarcaKeyTyped
        fieldmarca.setForeground(Color.black);
    }//GEN-LAST:event_fieldmarcaKeyTyped

    private void fieldplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldplacaKeyTyped
        fieldplaca.setForeground(Color.black);
    }//GEN-LAST:event_fieldplacaKeyTyped

    private void fieldmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldmodeloKeyTyped
        fieldmodelo.setForeground(Color.black);
    }//GEN-LAST:event_fieldmodeloKeyTyped

    private void fieldcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldcapacidadKeyTyped
        fieldcapacidad.setForeground(Color.black);
    }//GEN-LAST:event_fieldcapacidadKeyTyped

    public void insertDat(String marca, String modelo, String placa, int capacidad, String estado) {
        String query = "INSERT INTO vehiculos(MarcaVehiculo,ModeloVehiculo,PlacaVehiculo,CapacidadVehiculo,EstadoVehiculo) VALUES (?,?,?,?,?)";
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement enviarConsultas = cn.prepareStatement(query);
            enviarConsultas.setString(1, marca);
            enviarConsultas.setString(2, modelo);
            enviarConsultas.setString(3, placa);
            enviarConsultas.setInt(4, capacidad);
            enviarConsultas.setString(5, estado);
            enviarConsultas.executeUpdate();
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error" + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextField fieldcapacidad;
    private javax.swing.JComboBox<String> fieldestado;
    private javax.swing.JTextField fieldmarca;
    private javax.swing.JTextField fieldmodelo;
    private javax.swing.JTextField fieldplaca;
    private javax.swing.JLabel interrogacion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel rootvehi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object escucha = e.getSource();
        if (escucha == BotonLimpiar) {
            fieldmodelo.setText("");
            fieldplaca.setText("");
            fieldcapacidad.setText("");
            fieldmarca.setText(" ");

        }
    }
    
        @Override
    public void notificacion() {
        try {
            // Carga el archivo de sonido
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);

            // Obtiene el formato de audio
            AudioFormat format = audioStream.getFormat();

            // Crea una fuente de datos de audio
            DataLine.Info info = new DataLine.Info(Clip.class, format);

            // Abre el clip de audio
            Clip clip = (Clip) AudioSystem.getLine(info);
            clip.open(audioStream);

            // Agrega un LineListener para detectar cuando finaliza la reproducción del clip
            clip.addLineListener(new LineListener() {
                @Override
                public void update(LineEvent event) {
                    if (event.getType() == LineEvent.Type.STOP) {
                    }
                }
            });

            // Reproduce el sonido
            clip.start();
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException e) {
            e.printStackTrace();
        }
    }
    
 String soundFilePath = "C:\\Users\\chris\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\sonidos\\notificacion.wav";
    File sonido = new File(soundFilePath);
    String modelo;
    String placa;
    int capacidad;
    String marca;
    String estado;

}
