
package interfaz;

import java.awt.*;
import javax.swing.JOptionPane;
import java.sql.*;

public final class ConsultaVehiculos extends javax.swing.JFrame {

    
    public ConsultaVehiculos() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jPanel2.setBackground(Color.white);
        BotonVolver.setBackground(Color.white);
        BotonMostrar.setBackground(Color.white);
        setIconImage(getIconImage());
          setTitle("BDPaq");
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rootaltaconductor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaMostrar = new javax.swing.JTextArea();
        BotonVolver = new javax.swing.JButton();
        BotonMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldplaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rootaltaconductor.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(rootaltaconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 60, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 20));

        AreaMostrar.setEditable(false);
        AreaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        AreaMostrar.setColumns(20);
        AreaMostrar.setRows(5);
        AreaMostrar.setBorder(null);
        AreaMostrar.setFocusable(false);
        jScrollPane1.setViewportView(AreaMostrar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 130));

        BotonVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        BotonMostrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseExited(evt);
            }
        });
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 450, 60));

        jPanel3.setBackground(new java.awt.Color(45, 49, 66));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA VEHICULOS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajarob.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 360, 90));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matricula:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        fieldplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldplacaActionPerformed(evt);
            }
        });
        jPanel3.add(fieldplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        if (fieldplaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes introducir una matricula");
        } else {
            AreaMostrar.setText("");

            try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/paqueteria", "root", "")) {
                String sql = "SELECT * FROM vehiculos WHERE PlacaVehiculo = ?";
                PreparedStatement enviarConsultas = conexion.prepareStatement(sql);
                enviarConsultas.setString(1, fieldplaca.getText());
                ResultSet resultado = enviarConsultas.executeQuery();
                if (resultado.next()) {
                    id = resultado.getInt("IdVehiculo");
                    marca = resultado.getString("MarcaVehiculo");
                    modelo = resultado.getString("ModeloVehiculo");
                    placa = resultado.getString("PlacaVehiculo");
                    capacidad = resultado.getInt("CapacidadVehiculo");
                    estado = resultado.getString("EstadoVehiculo");

                    AreaMostrar.append("Id: " + id + "\n");
                    AreaMostrar.append("Marca: " + marca + "\n");
                    AreaMostrar.append("Modelo: " + modelo + "\n");
                    AreaMostrar.append("Placa: " + placa + "\n");
                    AreaMostrar.append("Capacidad: " + capacidad + "\n");
                    AreaMostrar.append("Estado: " + estado + "\n");

                }
            } catch (SQLException e) {
                System.out.println("Error al obtener los datos" + e.getMessage());
            }

        }

    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void fieldplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldplacaActionPerformed

    }//GEN-LAST:event_fieldplacaActionPerformed

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45,49,66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
       BotonVolver.setBackground(new Color(255,255,255));
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseEntered
      BotonMostrar.setBackground(new Color(45,49,66));
        BotonMostrar.setForeground(Color.white);
    }//GEN-LAST:event_BotonMostrarMouseEntered

    private void BotonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseExited
    BotonMostrar.setBackground(new Color(255,255,255));
        BotonMostrar.setForeground(Color.black);
    }//GEN-LAST:event_BotonMostrarMouseExited

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMostrar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextField fieldplaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel rootaltaconductor;
    // End of variables declaration//GEN-END:variables
    
    
    public int id;
    public String marca;
    public String modelo;
    public String placa;
    public int capacidad;
    public String estado;
}
