package interfaz;

import java.awt.Color;
import conexion.Conexion;
import java.awt.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author chris
 */
public class ConsultasPaquetes extends javax.swing.JFrame {

    public ConsultasPaquetes() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jPanel2.setBackground(Color.white);
        BotonVolver.setBackground(Color.white);
        BotonMostrar.setBackground(Color.white);
        setIconImage(getIconImage());
        rootpa.setText(menu.LabelRoot.getText());
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        BotonMostrar = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rootpa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaMostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fielddni = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(45, 49, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonMostrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseExited(evt);
            }
        });
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 80, -1));

        BotonVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 20));

        rootpa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rootpa.setForeground(new java.awt.Color(255, 255, 255));
        rootpa.setText("yy");
        jPanel2.add(rootpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 70, 20));

        AreaMostrar.setEditable(false);
        AreaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        AreaMostrar.setColumns(20);
        AreaMostrar.setRows(5);
        AreaMostrar.setFocusable(false);
        jScrollPane1.setViewportView(AreaMostrar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, 130));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA PAQUETES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 450, 60));

        jPanel3.setBackground(new java.awt.Color(45, 49, 66));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajarob.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI:");

        fielddni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fielddniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fielddni, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fielddni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        if (fielddni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes introducir un Dni");
        } else {
            AreaMostrar.setText("");

            try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/paqueteria", "root", "")) {
                String sql = "SELECT * FROM clientes JOIN paquetes ON clientes.IdCliente = paquetes.IdCliente WHERE clientes.DniCliente = ?";
                PreparedStatement enviarConsultas = conexion.prepareStatement(sql);
                enviarConsultas.setString(1, fielddni.getText());
                ResultSet resultado = enviarConsultas.executeQuery();
                if (resultado.next()) {
                    id = resultado.getInt("IdCliente");
                    String nombre = resultado.getString("NombreCliente");
                    tipo = resultado.getString("Tipo");
                    descripcion = resultado.getString("DescripcionPaquete");
                    fragil = resultado.getString("Fragil");
                    AreaMostrar.append("Id: " + id + "\n");
                    AreaMostrar.append("Descripcion: " + descripcion + "\n");
                    AreaMostrar.append("Tipo: " + tipo + "\n");
                    AreaMostrar.append("Fragil: " + fragil + "\n");

                } else {
                    JOptionPane.showMessageDialog(null, "Paquete no existente");
                }
            } catch (SQLException e) {
                System.out.println("Error al obtener los datos" + e.getMessage());
            }

        }


    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void fielddniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fielddniActionPerformed

    }//GEN-LAST:event_fielddniActionPerformed

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45, 49, 66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        BotonVolver.setBackground(new Color(255, 255, 255));
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseEntered
      BotonMostrar.setBackground(new Color(45,49,66));
        BotonMostrar.setForeground(Color.white);
    }//GEN-LAST:event_BotonMostrarMouseEntered

    private void BotonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseExited
        BotonMostrar.setBackground(new Color(255,255,255));
        BotonMostrar.setForeground(Color.black);
    }//GEN-LAST:event_BotonMostrarMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMostrar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fielddni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel rootpa;
    // End of variables declaration//GEN-END:variables

    public int id;
    public String tipo;
    public String descripcion;
    public String fragil;
    public String placavehiculo;
    VentanaMenu menu = new VentanaMenu();
}
