package interfaz;

import conexion.Conexion;
import java.awt.*;
import javax.swing.JOptionPane;
import java.sql.*;

public class ConsultaEnvios extends javax.swing.JFrame {

    public ConsultaEnvios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jPanel2.setBackground(Color.white);
        setIconImage(getIconImage());
        rootenv.setText(ventana.getNombreroot());
        setTitle("BDPaq");
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaMostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fielid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BotonMostrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        rootenv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(45, 49, 66));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaMostrar.setEditable(false);
        AreaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        AreaMostrar.setColumns(20);
        AreaMostrar.setRows(5);
        AreaMostrar.setBorder(null);
        AreaMostrar.setFocusable(false);
        jScrollPane1.setViewportView(AreaMostrar);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 120));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTAR ENVIOS");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajarob.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 250, 90));

        fielid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fielidActionPerformed(evt);
            }
        });
        jPanel4.add(fielid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Envio");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        BotonMostrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseExited(evt);
            }
        });
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 80, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 20));

        BotonVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        rootenv.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rootenv.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(rootenv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 450, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        if (fielid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes introducir una ID de envio");
        } else {
            AreaMostrar.setText(" ");
            try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/paqueteria", "root", "")) {
                String sql = "SELECT * FROM envios JOIN vehiculos ON envios.IdEnvio = vehiculos.IdVehiculo "
                        + "JOIN cond_vehi ON vehiculos.IdVehiculo = cond_vehi.IdVehiculo "
                        + "JOIN conductores ON cond_vehi.IdConductor =conductores.IdConductor WHERE envios.IdEnvio = ? ";
                PreparedStatement enviarConsultas = conexion.prepareStatement(sql);
                enviarConsultas.setInt(1, Integer.parseInt(fielid.getText()));

                ResultSet resultado = enviarConsultas.executeQuery();
                if (resultado.next()) {
                    idenvio = resultado.getInt("IdEnvio");
                    estado = resultado.getString("EstadoEnvio");
                    idvehiculo = resultado.getInt("IdVehiculo");
                    nombreconductor = resultado.getString("NombreConductor");
                    dniconductor = resultado.getString("DniConductor");
                    AreaMostrar.append("Id: " + idenvio + "\n");
                    AreaMostrar.append("Estado: " + estado + "\n");
                    AreaMostrar.append("Id Vehiculo: " + idvehiculo + "\n");
                    AreaMostrar.append("Nombre Conductor: " + nombreconductor + "\n");
                    AreaMostrar.append("Dni Conductor: " + dniconductor + "\n");
                }
            } catch (SQLException e) {
                System.out.println("Error al obtener los datos" + e.getMessage());
            }

        }

    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void fielidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fielidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fielidActionPerformed

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45, 49, 66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        BotonVolver.setBackground(new Color(255, 255, 255));
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseEntered
        BotonMostrar.setBackground(new Color(45, 49, 66));
        BotonMostrar.setForeground(Color.white);
    }//GEN-LAST:event_BotonMostrarMouseEntered

    private void BotonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseExited
        BotonMostrar.setBackground(new Color(255, 255, 255));
        BotonMostrar.setForeground(Color.black);
    }//GEN-LAST:event_BotonMostrarMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMostrar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextField fielid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel rootenv;
    // End of variables declaration//GEN-END:variables

    int idenvio;
    String estado;
    int idvehiculo;
    String nombreconductor;
    String dniconductor;
    VentanaMenu menu = new VentanaMenu();
    VentanaPrincipal ventana = new VentanaPrincipal();
}
