/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import conexion.Conexion;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author chris
 */
public class Reclamaciones extends javax.swing.JFrame {

    public Reclamaciones() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jPanel1.setBackground(Color.white);
        BotonMostrar.setEnabled(false);
        rootrecla.setText(menu.LabelRoot.getText());
        setIconImage(getIconImage());
        setTitle("BDPaq");
        //Boton a la escucha para que se deshabilite si no se pone un filtro
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BotonMostrar.setEnabled(true);

            }
        };
        filtroid.addActionListener(listener);
        filtroes.addActionListener(listener);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaMostrar = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        filtroid = new javax.swing.JRadioButton();
        filtroes = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        filtro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rootrecla = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        BotonMostrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaMostrar.setEditable(false);
        AreaMostrar.setColumns(20);
        AreaMostrar.setRows(5);
        AreaMostrar.setFocusable(false);
        jScrollPane1.setViewportView(AreaMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 490, 200));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(filtroid);
        filtroid.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        filtroid.setText("ID");
        filtroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroidActionPerformed(evt);
            }
        });
        jPanel3.add(filtroid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        buttonGroup3.add(filtroes);
        filtroes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        filtroes.setText("Estado");
        jPanel3.add(filtroes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 100, 40));

        filtro.setBackground(new java.awt.Color(248, 248, 248));
        filtro.setForeground(new java.awt.Color(204, 204, 204));
        filtro.setBorder(null);
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtroKeyTyped(evt);
            }
        });
        jPanel3.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Filtrar por:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 490, 200));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 10));

        jPanel5.setBackground(new java.awt.Color(45, 49, 66));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AREA RECLAMACIONES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 60));

        rootrecla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rootrecla.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(rootrecla, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 60, 60));

        BotonVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        BotonMostrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 600, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajaros.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 340));

        jButton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroidActionPerformed

    }//GEN-LAST:event_filtroidActionPerformed

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        if (filtroid.isSelected()) {
            ConsultarDatId();
        } else if (filtroes.isSelected()) {
            ConsultarDatEs();
        }


    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroKeyTyped
        filtro.setForeground(Color.black);
    }//GEN-LAST:event_filtroKeyTyped

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        BotonVolver.setBackground(new Color(45, 49, 66));
        BotonVolver.setForeground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        BotonVolver.setBackground(Color.white);
        BotonVolver.setForeground(Color.black);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMostrar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField filtro;
    private javax.swing.JRadioButton filtroes;
    private javax.swing.JRadioButton filtroid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel rootrecla;
    // End of variables declaration//GEN-END:variables

    public void ConsultarDatId() {
        AreaMostrar.setText("");
        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/paqueteria", "root", "")) {
            String query = "SELECT * FROM Reclamaciones WHERE IdReclamaciones = ?";
            PreparedStatement enviarConsultas = conexion.prepareStatement(query);
            enviarConsultas.setInt(1, Integer.parseInt(filtro.getText()));

            ResultSet resultado = enviarConsultas.executeQuery();
            if (resultado.next()) {
                id = resultado.getInt("IdReclamaciones");
                descripcion = resultado.getString("Descripcion");
                estado = resultado.getString("Estado");

                AreaMostrar.append("Id Reclamacion: " + id + "\n");
                AreaMostrar.append("Descripcion: " + descripcion + "\n");
                AreaMostrar.append("Estado: " + estado + "\n");

            }

        } catch (SQLException e) {
            System.err.println("Error al obtener los datos" + e.getMessage());
        }

    }

    public void ConsultarDatEs() {
        AreaMostrar.setText("");
        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/paqueteria", "root", "")) {
            String query = "SELECT * FROM Reclamaciones WHERE Estado = ?";
            PreparedStatement enviarConsultas = conexion.prepareStatement(query);
            enviarConsultas.setString(1, filtro.getText());

            ResultSet resultado = enviarConsultas.executeQuery();
            if (resultado.next()) {
                id = resultado.getInt("IdReclamaciones");
                descripcion = resultado.getString("Descripcion");
                estado = resultado.getString("Estado");

                //Creo un array y la convierto en matriz
                ArrayList<String> DatosArray = new ArrayList<String>();
                while (resultado.next()) {
                    String datos = resultado.getInt("IdReclamaciones") + " " + resultado.getString("Estado") + "\n" + "----------------------------------------------------";

                    DatosArray.add(datos);
                }
                String[] dataArray = DatosArray.toArray(new String[DatosArray.size()]);
                for (String datos : DatosArray) {
                    text = text + datos + "\n";
                }
                AreaMostrar.setText(text);
            }

        } catch (SQLException e) {
            System.err.println("Error al obtener los datos" + e.getMessage());
        }

    }

    String text;
    int id;
    String descripcion;
    String estado;
    VentanaMenu menu = new VentanaMenu();

}
