package interfaz;

import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.*;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author chris
 */
public final class VentanaMenu extends javax.swing.JFrame implements Interfaz, WindowListener {

    public VentanaMenu() {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());
        VentanaPrincipal ventana = new VentanaPrincipal();
        LabelRoot.setText(ventana.getNombreroot());
        setTitle("BDPaq");
        addWindowListener(this);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Panelcerrar = new javax.swing.JPanel();
        labelcerrarsesion = new javax.swing.JLabel();
        LabelRoot = new javax.swing.JLabel();
        labelroot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelLateral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonAltasEmp = new javax.swing.JButton();
        BotonConsulEmp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        BotonConsulClien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonAltaClien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Basedatos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 49, 66));

        Panelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelcerrarMouseEntered(evt);
            }
        });
        Panelcerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelcerrarsesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelcerrarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcerrarsesion.setText("Cerrar Sesión");
        labelcerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcerrarsesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelcerrarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelcerrarsesionMouseExited(evt);
            }
        });
        Panelcerrar.add(labelcerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        LabelRoot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LabelRoot.setForeground(new java.awt.Color(255, 255, 255));

        labelroot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelroot.setForeground(new java.awt.Color(255, 255, 255));
        labelroot.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelroot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(Panelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelroot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        PanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 490, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pajaros.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        PanelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -20, 430, 130));

        PanelLateral.setBackground(new java.awt.Color(255, 255, 255));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Area Empresa");
        PanelLateral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));

        BotonAltasEmp.setBackground(new java.awt.Color(253, 81, 45));
        BotonAltasEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonAltasEmp.setForeground(new java.awt.Color(255, 255, 255));
        BotonAltasEmp.setText("ALTAS");
        BotonAltasEmp.setBorder(null);
        BotonAltasEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltasEmpActionPerformed(evt);
            }
        });
        PanelLateral.add(BotonAltasEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 40));

        BotonConsulEmp.setBackground(new java.awt.Color(253, 81, 45));
        BotonConsulEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonConsulEmp.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsulEmp.setText("CONSULTAS");
        BotonConsulEmp.setBorder(null);
        BotonConsulEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsulEmpActionPerformed(evt);
            }
        });
        PanelLateral.add(BotonConsulEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        PanelLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 140, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logopequeño.png"))); // NOI18N
        PanelLateral.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 70));

        PanelPrincipal.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        BotonConsulClien.setBackground(new java.awt.Color(244, 247, 245));
        BotonConsulClien.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonConsulClien.setText("CONSULTAS");
        BotonConsulClien.setBorder(null);
        BotonConsulClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsulClienActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonConsulClien, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 140, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Area Clientes");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 160, 50));

        BotonAltaClien.setBackground(new java.awt.Color(244, 247, 245));
        BotonAltaClien.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonAltaClien.setText("ALTAS");
        BotonAltaClien.setBorder(null);
        BotonAltaClien.setFocusPainted(false);
        BotonAltaClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaClienActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonAltaClien, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 140, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 197, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoprincipal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 250, 440));

        MenuBar.setBorder(null);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Archivo");

        Basedatos.setText("Base de datos");
        Basedatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasedatosActionPerformed(evt);
            }
        });
        jMenu1.add(Basedatos);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BasedatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasedatosActionPerformed
        JPasswordField passwordField = new JPasswordField();
        int option = JOptionPane.showConfirmDialog(null, passwordField, "Contraseña acceso", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            String contra = new String(passwordField.getPassword());

            if (contra.equals("1234")) {
                try {
                    Desktop.getDesktop().browse(new URI("http://localhost/phpmyadmin/index.php?route=/database/structure&db=paqueteria"));
                } catch (IOException | URISyntaxException ex) {
                    System.out.println("Error: " + ex.getMessage());
                    Logger.getLogger(VentanaMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
            }
        }
    }//GEN-LAST:event_BasedatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BotonAltasEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltasEmpActionPerformed
        String[] options = {"Alta Conductor", "Alta Vehiculos"};
        int seleccion = JOptionPane.showOptionDialog(null, "Selecciona una opcion", "Altas",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        switch (seleccion) {
            case 0 -> {
                AltaConductores alta = new AltaConductores();
                alta.setVisible(true);
                this.dispose();
                alta.rootaltac.setText(LabelRoot.getText());
            }

            case 1 -> {
                Altavehi vehi = new Altavehi();
                vehi.setVisible(true);
                this.dispose();
            }
            default -> {
            }
        }

    }//GEN-LAST:event_BotonAltasEmpActionPerformed

    private void BotonConsulEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsulEmpActionPerformed
        String[] options = {"Vehiculos", "Envios", "Conductores"};
        int seleccion = JOptionPane.showOptionDialog(null, "Selecciona una opcion", "Consultas",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        switch (seleccion) {
            case 0 -> {
                VentanaPrincipal ventana = new VentanaPrincipal();
                ConsultaVehiculos consul = new ConsultaVehiculos();
                consul.rootaltaconductor.setText(ventana.getNombreroot());
                consul.setVisible(true);
                this.dispose();
            }
            case 1 -> {
                ConsultaEnvios envios = new ConsultaEnvios();
                envios.setVisible(true);
                this.dispose();
            }
            case 2 -> {
                ConsultaConductores consul = new ConsultaConductores();
                consul.setVisible(true);
                this.dispose();
            }
            default -> {
            }
        }


    }//GEN-LAST:event_BotonConsulEmpActionPerformed

    private void BotonConsulClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsulClienActionPerformed
        String[] options = {"Envios", "Paquetes", "Reclamaciones"};
        int seleccion2 = JOptionPane.showOptionDialog(null, "Selecciona una opcion", "Consultas",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        switch (seleccion2) {
            case 0 -> {
                ConsultaEnvios env = new ConsultaEnvios();
                env.setVisible(true);
                this.dispose();
            }
            case 1 -> {
                ConsultasPaquetes paq = new ConsultasPaquetes();
                paq.setVisible(true);
                this.dispose();
            }
            case 2 -> {
                Reclamaciones re = new Reclamaciones();
                re.setVisible(true);
                this.dispose();
            }
            default -> {
            }
        }

    }//GEN-LAST:event_BotonConsulClienActionPerformed

    private void BotonAltaClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaClienActionPerformed
        String[] options = {"Clientes", "Baja Clientes"};
        int seleccion2 = JOptionPane.showOptionDialog(null, "Selecciona una opcion", "Alta/Baja",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        switch (seleccion2) {
            case 0 -> {
                AltaClientes clien = new AltaClientes();
                clien.setVisible(true);
                this.dispose();
            }
            case 1 -> {
                BajaClientes baja = new BajaClientes();
                baja.setVisible(true);
                this.dispose();
            }
            default -> {
            }
        }

    }//GEN-LAST:event_BotonAltaClienActionPerformed

    private void PanelcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelcerrarMouseEntered

    }//GEN-LAST:event_PanelcerrarMouseEntered

    private void labelcerrarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarsesionMouseExited
        Panelcerrar.setBackground(Color.white);
        labelcerrarsesion.setForeground(Color.black);
    }//GEN-LAST:event_labelcerrarsesionMouseExited

    private void labelcerrarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarsesionMouseEntered

        Panelcerrar.setBackground(new Color(249, 72, 39));
        labelcerrarsesion.setForeground(Color.white);
    }//GEN-LAST:event_labelcerrarsesionMouseEntered

    private void labelcerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarsesionMouseClicked
        VentanaPrincipal ventana = new VentanaPrincipal();
        notificacion();
        JOptionPane.showMessageDialog(null, "Hasta luego!");
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelcerrarsesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Basedatos;
    private javax.swing.JButton BotonAltaClien;
    private javax.swing.JButton BotonAltasEmp;
    private javax.swing.JButton BotonConsulClien;
    private javax.swing.JButton BotonConsulEmp;
    public javax.swing.JLabel LabelRoot;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Panelcerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelcerrarsesion;
    public javax.swing.JLabel labelroot;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notificacion() {
        try {
            // Carga el archivo de sonido
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);

            // Obtiene el formato de audio
            AudioFormat format = audioStream.getFormat();

            // Crea una fuente de datos de audio
            DataLine.Info info = new DataLine.Info(Clip.class, format);

            // Abre el clip de audio
            Clip clip = (Clip) AudioSystem.getLine(info);
            clip.open(audioStream);

            // Agrega un LineListener para detectar cuando finaliza la reproducción del clip
            clip.addLineListener(new LineListener() {
                @Override
                public void update(LineEvent event) {
                    if (event.getType() == LineEvent.Type.STOP) {
                    }
                }
            });

            // Reproduce el sonido
            clip.start();
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException e) {
            e.printStackTrace();
        }
    }
    String soundFilePath = "C:\\Users\\chris\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\sonidos\\notificacion.wav";
    File sonido = new File(soundFilePath);
    public static String nom;
    boolean bandera = false;
    AltaClientes altac = new AltaClientes();

    @Override
    public void windowOpened(WindowEvent e) {

    }

    @Override
    public void windowClosing(WindowEvent e) {
        int res = JOptionPane.showConfirmDialog(null, "Estas seguro", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        } else {
            setDefaultCloseOperation(EXIT_ON_CLOSE);
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {

    }

    @Override
    public void windowIconified(WindowEvent e) {

    }

    @Override
    public void windowDeiconified(WindowEvent e) {

    }

    @Override
    public void windowActivated(WindowEvent e) {

    }

    @Override
    public void windowDeactivated(WindowEvent e) {

    }
}
